# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TestPokemonTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPokemonTask
  pod 'RealmSwift', '~>10'
  pod 'R.swift'

  target 'TestPokemonTaskTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift', '~>10'
    pod 'R.swift'
  end

  target 'TestPokemonTaskUITests' do
    # Pods for testing
    pod 'RealmSwift', '~>10'
    pod 'R.swift'
  end

end
